name: HACS

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hacs/action@main
        with:
          category: plugin
